### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [yagihashib/TC359_OneModelRailsApp#1]
I see a few issues I'd like you to fix here.

### Form errors styling

The styling on the navigation menu seems to also be affecting the form errors. Can you tweak your styling to make sure it's not overreaching?

### Avgfanduelpoints

I think `Avgfanduelpoints` could be renamed to something a little more readable to visitors. I was also able to enter in a negative number, which I don't *think* is desirable. [This Stack Overflow question](http://stackoverflow.com/questions/4416278/how-to-implement-min-max-validator-in-rails-3) should help you figure out how to fix this.

**Comment by yagihashib** [comment]
Hi Chris, I've pushed the changes to Github and Heroku. Let me know if
there are any more problems.

**Comment by chrisvfritz** [comment]
It looks like the form errors are still appearing inline, instead of in a normal list. To give you more context, the form errors would normally display in [a list like this](https://www.dropbox.com/s/firbgrr9nauwhq0/Screenshot%202015-04-01%2000.28.19.png?dl=0), but some overreaching styles in your `application.css` are making them appear [more like this](https://github.com/yagihashib/TC359_OneModelRailsApp/blob/master/app/assets/stylesheets/application.css).

Then the problem with readable labels for `Avgfanduelpoints` isn't really fixed by renaming the `avgfanduelpoints` attribute to `avgpoints`. I'd expect to see something more like `Average Points` when it's displayed to the visitor in a form label or table header, for example. The same goes for `Nbaplayer` actually. I can see that you're showing `NBA Player` sometimes, but not everywhere.

**Comment by yagihashib** [comment]
I've changed the styles so the form errors are consistent and have fixed
the labels and headers for better readability. Let me know how it looks.

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
